/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carproject;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class buy extends javax.swing.JFrame {

    /**
     * Creates new form buy
     */
    public buy() {
        initComponents();
        Show();
    }
     public ArrayList<user> userList(){
        ArrayList<user> userList=new ArrayList<>();
         try{
             String n=jTextField1.getText();
        Connection con =DriverManager.getConnection("jdbc:derby://localhost:1527/carproject","root","Nasusa9866@");
        String sql="select* from SELL where MODEL='"+n+"'";
         Statement st=  con.createStatement();
          ResultSet rs=   st.executeQuery(sql);
          user User;
          while(rs.next()){
              User=new user(rs.getString("MODEL"),rs.getString("NEOL"),rs.getString("PRICE"),rs.getString("NAME"),rs.getString("CC"));
              userList.add(User);
              
          }
    
         }catch(SQLException e)
{
JOptionPane.showMessageDialog(null,"something went wrong");
}
    
        return userList;
    } 
     public void Show(){
         ArrayList<user>list=userList();
         DefaultTableModel model=(DefaultTableModel)table.getModel();
         Object[] row=new Object[50];
         for(int i=0;i<list.size();i++){ 
             row[0]=list.get(i).getMODEL();
             row[1]=list.get(i).getNEOL();
             row[2]=list.get(i).getPRICE();
             row[3]=list.get(i).getNAME();
             row[4]=list.get(i).getCC();
             model.addRow(row);
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 30, 260, 30);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(360, 30, 120, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "car model", "F or  S", "Price", "Owner of car", "car number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 490, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Search a car to buy.....");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 180, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 10, 140, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("(Search cars only in small letters)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 70, 210, 15);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 310, 61, 23);
        jPanel1.add(canvas1);
        canvas1.setBounds(350, 310, 120, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\6777599-black-car-wallpaper.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       Show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        buyd bd=new buyd();
        bd.setVisible(true);
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        int i=table.getSelectedRow();
        String m=model.getValueAt(i,0).toString();
         String p=model.getValueAt(i,1).toString();
          String fs=model.getValueAt(i,2).toString();
          String o=model.getValueAt(i,3).toString();
         String no=model.getValueAt(i,4).toString();
         String s=jLabel3.getText();
        bd.jLabel1.setText(m);
         bd.jLabel5.setText(p);
          bd.jLabel4.setText(fs);
           bd.jLabel7.setText(o);
           bd.jLabel16.setText(s);
            try{
        
         
Connection con =DriverManager.getConnection("jdbc:derby://localhost:1527/carproject","root","Nasusa9866@");
             
String sql="select*from SELL where CC='"+no+"' ";
          Statement st=  con.createStatement();
             ResultSet rs=st.executeQuery(sql);
             while(rs.next()){
                 String km=rs.getString("KM");
                 String img=rs.getString("IMAGE");
                 String name=rs.getString("NAME");
                 String num=rs.getString("NUMB");
                 String sp=rs.getString("SPECIFICATION");
                 ImageIcon icon= new ImageIcon(img);
               
        Image image=icon.getImage().getScaledInstance(bd.jLabel10.getWidth(), bd.jLabel10.getHeight(),Image.SCALE_SMOOTH);
                 bd.jLabel8.setText(km);
                 bd.jLabel10.setIcon(icon);
                 bd.jLabel12.setText(no);
                 bd.jLabel14.setText(num);
                 bd.jTextArea1.setText(sp);
                 
                 
                
             }
            }catch(SQLException e)
{
JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
        welcome w=new welcome();
        w.setVisible(true);
        String n=jLabel3.getText();
        w.jLabel3.setText(n);
        Connection con =DriverManager.getConnection("jdbc:derby://localhost:1527/carproject","root","Nasusa9866@");
        String sql1="select*from DP where USERNAME='"+n+"' ";
         Statement st=  con.createStatement();
           ResultSet  rs=st.executeQuery(sql1);
             while(rs.next()){
                 
                 String img=rs.getString("IMG");
                 ImageIcon icon= new ImageIcon(img);
               
        Image image=icon.getImage().getScaledInstance(w.jLabel6.getWidth(), w.jLabel6.getHeight(),Image.SCALE_SMOOTH);
                 
                 w.jLabel6.setIcon(icon);
             }
        }catch(SQLException e){
                     JOptionPane.showMessageDialog(null,e);
                     }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    
}
