/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carproject;

import static carproject.JavaMailUtil.otp;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.math.BigInteger;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class credit extends javax.swing.JFrame {
int OTP;
PreparedStatement pst=null; 
    private static BigInteger  p;
    private static BigInteger  q; 
    private static BigInteger N; 
    private static  BigInteger phi;
    private static BigInteger e;
    private static BigInteger d;

private int	bitlength = 1024;
private Random	r;
static byte[] encrypted; 
static Random random = new Random();
static int otp = random.nextInt(999999);

    /**
     * Creates new form signin
     */
    public credit() {
        initComponents();
        
        r = new Random();

p = BigInteger.probablePrime(bitlength, r); 
q = BigInteger.probablePrime(bitlength, r); 
N = p.multiply(q);
phi = p.subtract(BigInteger.ONE).multiply(q.subtract(BigInteger.ONE));
e = BigInteger.probablePrime(bitlength / 2, r);
while (phi.gcd(e).compareTo(BigInteger.ONE) > 0 && e.compareTo(phi) < 0)

{

e.add(BigInteger.ONE);
}
d = e.modInverse(phi);
    }

public credit(BigInteger e, BigInteger d, BigInteger N)
{

this.e = e; this.d = d; this.N = N;
}

private static String bytesToString(byte[] encrypted)

{

String test = "";

for (byte b : encrypted)
{

test += Byte.toString(b);

}

return test;

}

public static byte[] encrypt(byte[] message)

{

return (new BigInteger(message)).modPow(e, N).toByteArray();

}

public static byte[] decrypt(byte[] message)
{

return (new BigInteger(message)).modPow(d, N).toByteArray();


 

    }
    /**
     * Creates new form credit
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public static void sendMail(String recepient) throws MessagingException{
        System.out.println("preparing to send email....");
        Properties properties = new Properties();
        
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");    
        
        String myAccountEmail = "noreplycarproject@gmail.com";
        String password = "Carproject9866@";
        
        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(myAccountEmail,password);
            }
        });
 
         Message message = prepareMessage(session, myAccountEmail, recepient);
         
         Transport.send(message);
         JOptionPane.showMessageDialog(null," Encrypted OTP has sended to your respective email id successfully...");
         System.out.println("Message sent successfully");
    }

    private static Message prepareMessage(Session session, String myAccountEmail,String recepient) {
         
        try{
            String name=jLabel8.getText();
            
            signin rsa = new signin();
            
            
            String ss=Integer.toString(otp);
            jLabel11.setText(ss);
            String en= jLabel11.getText();
            encrypted= rsa.encrypt(en.getBytes());
            byte[] numbe=bytesToString(en.getBytes()).getBytes();
            String enc=new String(numbe);
            byte[] decrypted = rsa.decrypt(encrypted);
            bytesToString(decrypted); 
            String S=new String(decrypted);
    
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(myAccountEmail));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(recepient));
            
            message.setSubject("OTP For Car Project :");
            message.setText("Hey There "+name +", \n \n \nYour encryted  OTP is : "+enc);
            return message;
        }catch (Exception ex) {
            Logger.getLogger(JavaMailUtil.class.getName()).log(Level.SEVERE,null, ex);
            System.out.println(ex);
        }
        return null;
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter Credit card details :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Card number :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Expiry date :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CVV :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Digital signature :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("ENCRYPTED OTP :");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField1.setText("XXXX-XXXX-XXXX-XXXX");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
        });

        jTextField2.setText("mm/yy");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField2MouseEntered(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField3.setText("CVV");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField3MouseEntered(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Send OTP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Encrypt and verify");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Decrypt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Enter Encrypted OTP to get receipt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel10)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton4))
                .addGap(35, 35, 35))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Continue to get receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(377, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(198, 198, 198)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(378, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(352, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(167, 167, 167)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(333, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(214, 214, 214)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseEntered
        // TODO add your handling code here:
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try { 
            String name=jLabel8.getText();
            Connection con =DriverManager.getConnection("jdbc:derby://localhost:1527/carproject","root","Nasusa9866@");
            String sql="select*from SIGNIN where username='"+name+"'";
         
            Statement st=  con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                        String email= rs.getString("MAILS");
			sendMail(email);
                        JOptionPane.showMessageDialog(null,"email sent you succesfully ");
                      }
                        /*String en= jLabel11.getText();
                        encrypted= rsa.encrypt(en.getBytes());
                        byte[] numbe=bytesToString(en.getBytes()).getBytes();
                        String enc=new String(numbe);
                        byte[] decrypted = rsa.decrypt(encrypted);
                        bytesToString(decrypted); 
                        String S=new String(decrypted);
    
                         jTextField6.setText(enc);*/
              
		} catch (Exception e) {
			 JOptionPane.showMessageDialog(null,"Error SMS "+e);
			
		}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        String n=jLabel8.getText();
        String no=jLabel9.getText();
        try{
            Connection con =DriverManager.getConnection("jdbc:derby://localhost:1527/carproject","root","Nasusa9866@");
            String sql="select*from SIGNIN where USERNAME='"+n+"'";
         
          Statement st=  con.createStatement();
             ResultSet rs=st.executeQuery(sql);
             
             while(rs.next()){
                 String p=rs.getString("PHONENUMB");
                 String a=rs.getString("ADDRESS");
                 String ds=rs.getString("DSD");
                 
                 
                 
                 
                 
                 String sql1="select*from SELL where CC='"+no+"'";
                  st=  con.createStatement();
                  rs=st.executeQuery(sql1);
                  while(rs.next()){
                       String na=rs.getString("MODEL");
                       String k=rs.getString("KM");
                       String pr=rs.getString("PRICE");
                       String s=rs.getString("SPECIFICATION");
                       String fs=rs.getString("NEOL");
                        String y=rs.getString("Y");
                        String num=rs.getString("NUMB");
                        String o=rs.getString("NAME");
                        
                        
                   
                   int O=otp;
            if(Integer.parseInt(jTextField6.getText())==O){
 JOptionPane.showMessageDialog(null,"OTP is successfully verified click ok to get receipt");
  receipt r=new receipt();
 r.setVisible(true);
 
 
 r.area.setText(r.area.getText()+"*********************************************************\n");
 r.area.setText(r.area.getText()+"                       ONLINE CAR PUCHASING RECEIPT           \n");
 r.area.setText(r.area.getText()+"*********************************************************\n");
SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy ");  
 Date date = new Date();  
 r.area.setText(r.area.getText()+"                                                                  " +date+ "\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+" your details :\n");
 r.area.setText(r.area.getText()+" --------------\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"              Name :" +n+ "\n"); 
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"Phone number :" +p+ "\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"Address :" +a+ "\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"                                            "       +ds+"\n");
 r.area.setText(r.area.getText()+"                                       ******************\n");
 r.area.setText(r.area.getText()+"                                        Digital Signature\n");
 r.area.setText(r.area.getText()+"*********************************************************\n");
 r.area.setText(r.area.getText()+      " Car details :\n");
 r.area.setText(r.area.getText()+" --------------\n");
 r.area.setText(r.area.getText()+"                                                      "+fs+"     \n");
 r.area.setText(r.area.getText()+"Car name :           " +na+ "\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"Car number :         " +no+ "\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"Year of manufacture :          " +y+ "\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"kilometer travelled :" +k+ "\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"car problem :        " +s+ "\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"Car price :          " +pr+ "\n");
 r.area.setText(r.area.getText()+"*********************************************************\n");
 r.area.setText(r.area.getText()+"                 To contact owner  "+num+"                    \n");
 r.area.setText(r.area.getText()+"*********************************************************\n");
 r.area.setText(r.area.getText()+"\n");
 r.area.setText(r.area.getText()+"                      *THANK YOU FOR SHOPPING*                    \n");
 
 String sql2="insert into SOLD(NAME,CAR,PRICE,FRS,CARNO,OWNER,ONO) values('"+n+"','"+na+"','"+pr+"','"+fs+"','"+no+"','"+o+"','"+num+"')";
 st=  con.createStatement();
                  st.executeUpdate(sql2);
                  
                  
                  String sql3="delete from SELL where CC='"+no+"'";
                  st=  con.createStatement();
                  st.executeUpdate(sql3);
                  
 }
 else
 {
 JOptionPane.showMessageDialog(null,"wrong OTP");

 }
             }
             }
        }catch(SQLException e)
{
JOptionPane.showMessageDialog(null,e);
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseEntered
        // TODO add your handling code here:
        jTextField3.setText("");
    }//GEN-LAST:event_jTextField3MouseEntered

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        signin rsa = new signin(); 
        String n=jLabel8.getText();
    String en= jTextField7.getText();
    JOptionPane.showMessageDialog(null, "Encrypted sucessfully message is	"+"  "+bytesToString(en.getBytes()));
    encrypted= rsa.encrypt(en.getBytes());
    byte[] numbe=bytesToString(en.getBytes()).getBytes();
             String enc=new String(numbe);
    //JOptionPane.showMessageDialog(null, "Encrypted form is	" +" "+ encrypted);
    byte[] decrypted = rsa.decrypt(encrypted);
bytesToString(decrypted); 
String S=new String(decrypted);
//JOptionPane.showMessageDialog(null, "Decrypted form is	"+" " + S);
JOptionPane.showConfirmDialog(this, "click yes to verify the signature", "confirm", JOptionPane.YES_NO_OPTION);

Connection con =DriverManager.getConnection("jdbc:derby://localhost:1527/carproject","root","Nasusa9866@");

String sql="select*from SIGNIN where USERNAME='"+n+"' ";
          Statement st=  con.createStatement();
             ResultSet rs=st.executeQuery(sql);
             while(rs.next()){
                 String de=rs.getString("DSE");
             
             if(enc.equals(de)){
                 
                 JOptionPane.showMessageDialog(null, "successfully verified	"+" " + S);
             }else{
                  JOptionPane.showMessageDialog(null, "wrong signature you are trying to duplicate");
                  jTextField7.setText("");
             }
             }

        }catch(SQLException e)
{
JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        signin rsa = new signin();
        String en= jLabel11.getText();
        encrypted= rsa.encrypt(en.getBytes());
        byte[] decrypted = rsa.decrypt(encrypted);
        
bytesToString(decrypted); 
String S=new String(decrypted);
jTextField6.setText(S);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new credit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private static javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
