/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carproject;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class retur extends javax.swing.JFrame {

    /**
     * Creates new form retur
     */
    public retur() {
        initComponents();
        Show();
    }
     public ArrayList<returnn> userList(){
        ArrayList<returnn> userList=new ArrayList<>();
         try{
             String n= jLabel1.getText();
        Connection con =DriverManager.getConnection("jdbc:derby://localhost:1527/carproject","root","Nasusa9866@");
        String sql="select* from SOLD where NAME='"+n+"' ";
         Statement st=  con.createStatement();
          ResultSet rs=   st.executeQuery(sql);
          returnn Users;
          while(rs.next()){
              Users=new returnn(rs.getString("NAME"),rs.getString("CAR"),rs.getString("PRICE"),rs.getString("FRS"),rs.getString("CARNO"),rs.getString("OWNER"),rs.getString("ONO"));
              userList.add(Users);
              
          }
    
         }catch(SQLException e)
{
JOptionPane.showMessageDialog(null,"something went wrong");
}
    
        return userList;
    } 
     public void Show(){
         ArrayList<returnn>list=userList();
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         Object[] row=new Object[50];
         for(int i=0;i<list.size();i++){ 
             row[0]=list.get(i).getNAME();
             row[1]=list.get(i).getCAR();
             row[2]=list.get(i).getPRICE();
             row[3]=list.get(i).getFRS();
             row[4]=list.get(i).getCARNO();
             row[5]=list.get(i).getOWNER();
             row[6]=list.get(i).getONO();
             
             model.addRow(row);
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "car name", "price", "F or S", "car number", "owner", "owner number"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Back");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         returnd bd=new returnd();
        bd.setVisible(true);
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int i=jTable1.getSelectedRow();
        String n=model.getValueAt(i,0).toString();
         String cn=model.getValueAt(i,1).toString();
          String pr=model.getValueAt(i,2).toString();
          String fs=model.getValueAt(i,3).toString();
         String cno=model.getValueAt(i,4).toString();
         String o=model.getValueAt(i,5).toString();
         String ono=model.getValueAt(i,6).toString();
         
        bd.jLabel2.setText(n);
         bd.jLabel4.setText(cn);
          bd.jLabel6.setText(pr);
           bd.jLabel8.setText(fs);
           bd.jLabel10.setText(cno);
            bd.jLabel12.setText(o);
             bd.jLabel14.setText(ono);
            try{
        
         
Connection con =DriverManager.getConnection("jdbc:derby://localhost:1527/carproject","root","Nasusa9866@");
             
String sql="select*from SELL where CC='"+cno+"' ";
          Statement st=  con.createStatement();
             ResultSet rs=st.executeQuery(sql);
             while(rs.next()){
                // String km=rs.getString("KM");
                 String img=rs.getString("IMAGE");
                 //String name=rs.getString("NAME");
                 //String num=rs.getString("NUMB");
                 //String sp=rs.getString("SPECIFICATION");
                 ImageIcon icon= new ImageIcon(img);
               
       // Image image=icon.getImage().getScaledInstance(bd.jLabel15.getWidth(), bd.jLabel15.getHeight(),Image.SCALE_SMOOTH);
                 //bd.jLabel8.setText(km);
                 //bd.jLabel15.setIcon(icon);
                 //bd.jLabel12.setText(no);
                 //bd.jLabel14.setText(num);
                 //bd.jTextArea1.setText(sp);
                 
                 
                
             }
            }catch(SQLException e)
{
JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new retur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
